# Model size and learning parameters are inspired from https://github.com/karpathy/llama2.c 
# and Super Tiny Language Models paper https://arxiv.org/pdf/2405.14159v1

exp_name: fsdp_1b
num_steps: 25000
eval_steps: -1
evalulation_interval: 500
dp_world_size: 8
batch_size: 128
log_dir: /home/gensyn/shared/experiments
transformer_engine: true

train_data_loader:
  _target_: noloco.data_loaders.ShardedDataset
  path: /home/gensyn/shared/data/training_data/*.parquet

validation_data_loaders:
  dev:
    _target_: noloco.data_loaders.ShardedDataset
    path: /home/gensyn/shared/data/validation_data/*.parquet

# intermediate_size = 4 x hidden_size
model:
  _target_: noloco.pipeline_llama.DiPaCoLlamaBuilder
  hidden_size: 2048
  intermediate_size: 8192
  num_attention_heads: 32
  num_hidden_layers: 24

optimizer:
  _target_: noloco.dp_optimizer.DataParallelOptimizerBuilder
  lr: 2e-4

scheduler:
  _target_: noloco.schedulers.CosineWarmupLRBuilder
  min_lr: 2e-5
  max_steps: 25000
  warmup_steps: 1000
